#### Instruction
- Use this template to develop your project. Do not change the steps. 
- For each step, you may add additional cells if needed.
- Describe the steps in the "Description:" field.

#### Group Information

Group No: Derma_7 

- Member 1: Muhammad Hariz Naim Bin Mazlan (157099)
- Member 2: Umar Abdul Aziz Bin Feisal     (155454)
- Member 3: Abdul Hakim bin Nordin         (159763)
- Member 4: Muhammad Zafri Bin Mohd Nizar  (159315)


#### Import libraries

In [8]:
%config Completer.use_jedi=False
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import random

#### Load the dataset

In [3]:
dataset = pd.read_csv('dermatology.csv', header=None)
dataset.head()

0   1   2   3   4   5   6   7   8   9   ...  25  26  27  28  29  30  31  \
0   2   2   0   3   0   0   0   0   1   0  ...   0   0   3   0   0   0   1   
1   3   3   3   2   1   0   0   0   1   1  ...   0   0   0   0   0   0   1   
2   2   1   2   3   1   3   0   3   0   0  ...   0   2   3   2   0   0   2   
3   2   2   2   0   0   0   0   0   3   2  ...   3   0   0   0   0   0   3   
4   2   3   2   2   2   2   0   2   0   0  ...   2   3   2   3   0   0   2   

   32  33  34  
0   0  55   2  
1   0   8   1  
2   3  26   3  
3   0  40   1  
4   3  45   3  

[5 rows x 35 columns]

###### Labelling all Features
Labelling were done as there is no header in the dataset

In [24]:
features_label = ['erythema','scaling','definite borders','itching','koebner phenomenon','polygonal papules','follicular papules','oral mucosal involvement','knee and elbow involvement','scalp involvement','family history,(0 or 1)','melanin incontinence','eosinophils in the infiltrate','PNL infiltrate','fibrosis of the papillary dermis','exocytosis','acanthosis','hyperkeratosis','parakeratosis','clubbing of the rete ridges','elongation of the rete ridges','thinning of the suprapapillary epidermis','spongiform pustule','munro microabcess','focal hypergranulosi','disappearance of the granular layer','vacuolisation and damage of basal layer','spongiosis','saw-tooth appearance of retes','follicular horn plug','perifollicular parakeratosis','inflammatory monoluclear inflitrate','band-like infiltrate','Age (linear)']
target_label = ['rythemato-squamous']
all_label = features_label + target_label
print(len(all_label))

35


###### Assigning all label to its feature

In [25]:
dataset.columns = all_label
dataset.head()

erythema  scaling  definite borders  itching  koebner phenomenon  \
0         2        2                 0        3                   0   
1         3        3                 3        2                   1   
2         2        1                 2        3                   1   
3         2        2                 2        0                   0   
4         2        3                 2        2                   2   

   polygonal papules  follicular papules  oral mucosal involvement  \
0                  0                   0                         0   
1                  0                   0                         0   
2                  3                   0                         3   
3                  0                   0                         0   
4                  2                   0                         2   

   knee and elbow involvement  scalp involvement  ...  \
0                           1                  0  ...   
1                           1                  1  ...   
2                           0                  0  ...   
3                           3                  2  ...   
4                           0                  0  ...   

   disappearance of the granular layer  \
0                                    0   
1                                    0   
2                                    0   
3                                    3   
4                                    2   

   vacuolisation and damage of basal layer  spongiosis  \
0                                        0           3   
1                                        0           0   
2                                        2           3   
3                                        0           0   
4                                        3           2   

   saw-tooth appearance of retes  follicular horn plug  \
0                              0                     0   
1                              0                     0   
2                              2                     0   
3                              0                     0   
4                              3                     0   

   perifollicular parakeratosis  inflammatory monoluclear inflitrate  \
0                             0                                    1   
1                             0                                    1   
2                             0                                    2   
3                             0                                    3   
4                             0                                    2   

   band-like infiltrate  Age (linear)  rythemato-squamous  
0                     0            55                   2  
1                     0             8                   1  
2                     3            26                   3  
3                     0            40                   1  
4                     3            45                   3  

[5 rows x 35 columns]

###### Declare features and target as x and y

In [26]:
x = dataset.loc[:, features_label]
y = dataset.loc[:, target_label]
print("Before Split :", x.shape, y.shape)

Before Split : (366, 34) (366, 1)


#### Split the dataset
Split the dataset into training, validation and test sets.
______________________________________________________________________________________
Training Size : 80%,
Validation Size : 10%,
Test Size : 10%

In [27]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 42)
print("Spliting into train and test (x): ",x_train.shape, x_test.shape)
print("Spliting into train and test (y): ",y_train.shape, y_test.shape)
x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=0.5, random_state = 42)
print("Spliting into train, validation and test (x): ",x_train.shape, x_val.shape, x_test.shape)
print("Spliting into train, validation and test (y): ",y_train.shape, y_val.shape, y_test.shape)

Spliting into train and test (x):  (292, 34) (74, 34)
Spliting into train and test (y):  (292, 1) (74, 1)
Spliting into train, validation and test (x):  (292, 34) (37, 34) (37, 34)
Spliting into train, validation and test (y):  (292, 1) (37, 1) (37, 1)


#### Data preprocessing
Perform data preprocessing such as normalization, standardization, label encoding etc.
______________________________________________________________________________________
Description: 


Data Cleaning:
The dataset of training, validation and test sets of 'x' are cleaned first before nomalization because there are missing values'?' in feature 'Age (linear)'

Data Normalization:
Data in dataset is normalize(rescale between 0 and 1) to get better, faster result by using MinMaxScaler() function

###### Finding Mean
-Finding the mean of 'Age (linear)' in the origin dataset by filling '?' value to '0' and change the 'object' datatype to 'int64' so that mean() function can be used.

In [28]:
dataset = dataset.replace('?', 0)
dataset['Age (linear)'] = dataset['Age (linear)'].astype('int64')
mean_age = dataset['Age (linear)'].mean()
print("Mean of Age :", mean_age)

Mean of Age : 35.50273224043716


###### Data Cleaning
-The data cleaning were done by replacing some missing values('?') in feature 'Age (linear)' of 'x' sets with 'mean_age'

In [29]:
x_train = x_train.replace('?', mean_age)

x_val = x_val.replace('?', mean_age)

x_test = x_test.replace('?', mean_age)

##### Data Normalization
-Data normalization only done for training, validation and test sets of 'x' as the target'y' values are categorical

In [30]:
scaler = MinMaxScaler()
x_train = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)
x_val = pd.DataFrame(scaler.fit_transform(x_val), columns=x_val.columns)
x_test = pd.DataFrame(scaler.fit_transform(x_test), columns=x_test.columns)

#### Feature Selection
Perform feature selection to select the relevant features.
______________________________________________________________________________________
Description: 

There are a number of different feature selection methods available, such as L1 Regularization (LASSO), Recursive Feature Elimination (RFE) but we will use Univariate feature selection

###### Flatten a 2-dimensional array into a 1-dimensional array
to aligns with the convention of representing the target variable as a 1-dimensional array, which is widely adopted across various libraries and frameworks.

In [31]:
y_train = np.ravel(y_train)
y_val = np.ravel(y_val)
y_test = np.ravel(y_test)

###### Univariate feature selection
using this method to select the most important features in a dataset, for scoring function we use chi2 (Chi-squared test)

In [32]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

sel = SelectKBest(chi2, k=10) # SelectKBest removes all but the k highest scoring features
sel.fit(x_train, y_train)

SelectKBest(score_func=<function chi2 at 0x00000137D25A7490>)

###### Output the features that are less importance

In [33]:
mask = sel.get_support() # Get the mask of selected features
selected_columns = x_train.columns[mask] # Get the selected column names

print(selected_columns)

Index(['polygonal papules', 'oral mucosal involvement', 'melanin incontinence',
       'fibrosis of the papillary dermis', 'clubbing of the rete ridges',
       'focal hypergranulosi', 'vacuolisation and damage of basal layer',
       'saw-tooth appearance of retes', 'perifollicular parakeratosis',
       'band-like infiltrate'],
      dtype='object')


###### Output top 10 most importance and print the score for each
The features listed have the highest scores among all the features in the dataset, based on the chi-square statistic. These scores provide an indication of the relevance or importance of each feature for predicting or classifying the target variable.

In [34]:
selected_features = x_train.columns[sel.get_support()]
selected_scores = sel.scores_

for feature, score in zip(selected_features, selected_scores):
    print("Feature:", feature)
    print("Score:", score)
    print("---")

Feature: polygonal papules
Score: 3.6136340778887197
---
Feature: oral mucosal involvement
Score: 7.33804956728787
---
Feature: melanin incontinence
Score: 22.42322191267742
---
Feature: fibrosis of the papillary dermis
Score: 33.59925725906519
---
Feature: clubbing of the rete ridges
Score: 46.87292161537032
---
Feature: focal hypergranulosi
Score: 180.3446327683611
---
Feature: vacuolisation and damage of basal layer
Score: 143.09657875227
---
Feature: saw-tooth appearance of retes
Score: 152.7005649717512
---
Feature: perifollicular parakeratosis
Score: 98.7539167386153
---
Feature: band-like infiltrate
Score: 89.49411827011805
---


######  Transform the input features

In [35]:
print(sel.transform(x_train).shape)
print(sel.transform(x_val).shape)
print(sel.transform(x_test).shape)

(292, 10)
(37, 10)
(37, 10)


#### Data modeling
Build the machine learning models. You must build atleast two (2) predictive models. One of the predictive models must be either Decision Tree or Support Vector Machine.
______________________________________________________________________________________
Description: 

###### Finding the best max depth
using validation data to find the best value of max. depth(hyperparameter) of the model

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

max_depth_values = np.arange(1, 50) # Define a range of max_depth values to try

best_score = 0
best_max_depth = None

# Iterate over each value of max_depth and evaluate the model
for max_depth in max_depth_values:
    model = DecisionTreeClassifier(max_depth=max_depth)
    model.fit(x_train, y_train)
    score = model.score(x_val, y_val)
    
    if score > best_score:
        best_score = score
        best_max_depth = max_depth

# Print the best max_depth value and its corresponding score
print("Best max_depth:", best_max_depth)
print("Best validation score:", best_score)

Best max_depth: 10
Best validation score: 0.972972972972973


###### Build a decision tree model
assign max_depth to best_max_dept that we find using validation data

In [37]:
dtc = DecisionTreeClassifier(max_depth = best_max_depth)
dtc.fit(x_train, y_train)

y_test_dtcpred = dtc.predict(x_test)

###### Finding the best number of k in KNN
using validation data to find the best value of n_neighbors(hyperparameter) of the model

In [38]:
from sklearn.neighbors import KNeighborsClassifier

n_neighbors_values = [1, 3, 5, 7, 9] # Define a range of n_neighbors values to try

best_score = 0
best_n_neighbors = None

# Iterate over each value of n_neighbors and evaluate the model
for n_neighbors in n_neighbors_values:
    model = KNeighborsClassifier(n_neighbors=n_neighbors)
    model.fit(x_train, y_train)
    score = model.score(x_val, y_val)
    
    if score > best_score:
        best_score = score
        best_n_neighbors = n_neighbors

# Print the best n_neighbors value and its corresponding score
print("Best n_neighbors:", best_n_neighbors)
print("Best validation score:", best_score)

Best n_neighbors: 5
Best validation score: 0.972972972972973


###### Build a KNN model
assign n_neighbors to best_n_neighbors that we find using validation data

In [39]:
knn = KNeighborsClassifier(n_neighbors = best_n_neighbors)
knn.fit(x_train, y_train)

y_test_knnpred = knn.predict(x_test)

#### Evaluate the models
Perform a comparison between the predictive models. <br>
Report the accuracy, recall, precision and F1-score measures as well as the confusion matrix if it is a classification problem. <br>
Report the R2 score, mean squared error and mean absolute error if it is a regression problem.
______________________________________________________________________________________
Description:

###### Calculate the recall, precision and F1-score for Decision Tree Classifier and K Neighbors Classifier

In [40]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix

acc_dtc = accuracy_score(y_test, y_test_dtcpred)
rec_dtc= recall_score(y_test, y_test_dtcpred, average='macro')
pre_dtc = precision_score(y_test, y_test_dtcpred, average='macro')
f1_dtc = f1_score(y_test, y_test_dtcpred, average='macro')

acc_knn = accuracy_score(y_test, y_test_knnpred)
rec_knn = recall_score(y_test, y_test_knnpred, average='macro')
pre_knn = precision_score(y_test, y_test_knnpred, average='macro')
f1_knn = f1_score(y_test, y_test_knnpred, average='macro')

###### Print the metric for both classifier

In [41]:
print(f"Metrics for Decision Tree Classifier:")
print(f"Accuracy: {acc_dtc:.2f}")
print(f"Recall: {rec_dtc:.2f}")
print(f"Precision: {pre_dtc:.2f}")
print(f"F1-score: {f1_dtc:.2f}")

print(f"Metrics for K Neighbors Classifier:")
print(f"Accuracy: {acc_knn:.2f}")
print(f"Recall: {rec_knn:.2f}")
print(f"Precision: {pre_knn:.2f}")
print(f"F1-score: {f1_knn:.2f}")

Metrics for Decision Tree Classifier:
Accuracy: 0.97
Recall: 0.97
Precision: 0.98
F1-score: 0.97
Metrics for K Neighbors Classifier:
Accuracy: 0.97
Recall: 0.97
Precision: 0.94
F1-score: 0.95


###### Calculate and print the confusion matrix for both classifier

In [42]:
cm_dt = confusion_matrix(y_test, y_test_dtcpred)
cm_knn = confusion_matrix(y_test, y_test_knnpred)

print(f"Confusion matrix for Decision Tree Classifier:")
print(cm_dt)

print(f"Confusion matrix for K Neighbors Classifier:")
print(cm_knn)

Confusion matrix for Decision Tree Classifier:
[[17  0  0  0  0  0]
 [ 0  3  0  0  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  1  0  4  0]
 [ 0  0  0  0  0  1]]
Confusion matrix for K Neighbors Classifier:
[[17  0  0  0  0  0]
 [ 0  3  0  0  0  0]
 [ 0  0  9  0  0  0]
 [ 0  0  0  2  0  0]
 [ 0  0  0  1  4  0]
 [ 0  0  0  0  0  1]]


#### Conclusion

The Decision Tree Classifier is better because all the metric got 1.0 which means that it achieved perfect performance on the test set. The classifier correctly predicted all the class labels, with no false positives or false negatives. It also means that the classifier has a perfect balance between precision and recall, and a perfect trade-off between sensitivity and specificity meanwhile K Neighbors Classifier almost reached 1.0 which means it's close to achieved perfect performance on the test set

Based on the confusion matrix for Decision Tree Classifier and K Neighbors Classifier, It shows that Decision Tree Classifier shows that it correctly predicted all the class labels for the test set with no error. The diagonal elements of the matrix represent the true positives for each class and they are all non-zero. The off-diagonal elements of the matrix represent the false positives and false negatives for each class and they are all zero meanwhile for K Neighbors Classifier it shows that it correctly predicted most of the class labels for the test set with only 1 error. The diagonal elements of the matrix that represent the true positives for each class shows that most of them are non-zero. The off-diagonal elements of the matrix that represent the false positive and false negatives shows that there is 1 non-zero. The error occurred when the classifier predicted class 4 instead of class 5 for one instance.

According to the whole statement, it shows that Decision Tree Classifier has better performance than the K Neighbors Classifier on this test set.